//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exentials.Snw {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exentials.Snw.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type {0}.
        /// </summary>
        public static string ArgumentMustBeOfType {
            get {
                return ResourceManager.GetString("ArgumentMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code was generated automatically by Exentials SnwConnector.
        /// </summary>
        public static string CodeGeneration {
            get {
                return ResourceManager.GetString("CodeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter&apos;s length exceed {0}.
        /// </summary>
        public static string MaxParameterLengthError {
            get {
                return ResourceManager.GetString("MaxParameterLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABAP exception..
        /// </summary>
        public static string RFC_ABAP_EXCEPTION {
            get {
                return ResourceManager.GetString("RFC_ABAP_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABAP runtime error. {0} .
        /// </summary>
        public static string RFC_ABAP_RUNTIME_FAILURE {
            get {
                return ResourceManager.GetString("RFC_ABAP_RUNTIME_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication failure with the host..
        /// </summary>
        public static string RFC_COMMUNICATION_FAILURE {
            get {
                return ResourceManager.GetString("RFC_COMMUNICATION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter..
        /// </summary>
        public static string RFC_INVALID_PARAMETER {
            get {
                return ResourceManager.GetString("RFC_INVALID_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on failure, wrong user name or password..
        /// </summary>
        public static string RFC_LOGON_FAILURE {
            get {
                return ResourceManager.GetString("RFC_LOGON_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is already open.
        /// </summary>
        public static string RfcConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("RfcConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is not open..
        /// </summary>
        public static string RfcConnectionIsNotOpen {
            get {
                return ResourceManager.GetString("RfcConnectionIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad DLL format. Libraries for {0} platform are required..
        /// </summary>
        public static string RfcDllBadFormat {
            get {
                return ResourceManager.GetString("RfcDllBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPNWRFC.DLL or related files not found..
        /// </summary>
        public static string RfcDllNotFound {
            get {
                return ResourceManager.GetString("RfcDllNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid handle connection..
        /// </summary>
        public static string RfcInvalidHandle {
            get {
                return ResourceManager.GetString("RfcInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not handled..
        /// </summary>
        public static string TypeNotHandled {
            get {
                return ResourceManager.GetString("TypeNotHandled", resourceCulture);
            }
        }
    }
}
